baseURL = 'https://joined.github.io/'
languageCode = 'en-us'
title = "Lorenzo Gasparini's site"
theme = ['hugo-notice', 'cactus']

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[markup]
[markup.highlight]
style = "catppuccin-latte"

[params]
description = "Hi! I'm Lorenzo Gasparini, a Full-Stack Web Developer based in Berlin, Germany."
logo = "images/avatar.jpg"
[[params.social]]
name = "github"
link = "https://github.com/joined"
[[params.social]]
name = "linkedin"
link = "https://www.linkedin.com/joined/"

[caches]
[caches.images]
dir = ':cacheDir/images'
